import Background from "@/components/Background";
import Header from "@/components/Header";
import type { Metadata } from "next";
import "./globals.css";
import styles from "./home.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <Header />
        {/* <Background /> */}
        <div className={styles.container}>{children}</div>
      </body>
    </html>
  );
}
